sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
  ssh_known_hosts:
    - web.sourceforge.net

language: java

jdk: oraclejdk8

before_install:
  - "mkdir -p $HOME/.m2"
  - "cp .travis/travis-settings.xml $HOME/.m2/settings.xml"
  - "mkdir -p $HOME/.ssh"
  - "openssl aes-256-cbc -K $encrypted_4ffa600c8269_key -iv $encrypted_4ffa600c8269_iv -in .travis/id_rsa.enc -out $HOME/.ssh/id_rsa -d"
  - "chmod 600 $HOME/.ssh/id_rsa"
install: true
before_script:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3 # give xvfb some time to start

script: "bash .travis/build.sh"


before_deploy: true
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file:
  - net.sourceforge.pmd.eclipse.p2updatesite/target/net.sourceforge.pmd.eclipse.p2updatesite-*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: pmd/pmd-eclipse-plugin
    condition: "${TRAVIS_SECURE_ENV_VARS} = true"
after_deploy: bash .travis/release.sh



notifications:
  email:
    recipients:
    - adangel@users.sourceforge.net
    on_success: always
    on_failure: always
cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - secure: "nlH1I4vtTWSk2SDxzw0SzSRv9lQy1SuvwF9njO6OABDFwK3RWRmAFhsEcdQ/V7SdLJ24FJjw1qVOMVW8ZroytQx2b035ipBMFkZtWM6KJoJ4DpMjEW5x9Q9aBIaETOa5EPK/6p4cGce1L97nUU3t9d4NFbUK3+RDg2mhEz9Iy0wbGO1qW+d0oKO2+Pm97ZWJCMTgk7hfpgSUiHKsjH3jLF2yCZRfu7IQ6fkXkjxtCuzccCelO784aW4UmTZCiXgKFyxUjdDc5JnuiFw4zDbUl/gPmAGPi6HCCtwuRBUNMkP6Xcp4/3OL3mNEAHr9snqpsAK6e8jnMB0HqdxOMIlHy0JQjelP27Eh+YlEgQr9SZ3jGb7iLc+1ibn9e3wp2jP9ezyfacxsQnXOxtFSLxdnp95G6iAL4Pxe/UoLz5YInxtdxrft4p0ETzbraX1stqecN3A6/mGlMSfNzkdikMvvVung0KXiNZzOw6DW4auMt/rwkf3vt/Ebl8jDMSZaoLLnDdRisuPyGbj3YhtPhJ3uLRmULqcOIjcN74/ODZhM2D1p8br+B5pqa7gBDBzo+o6s6LP7IZvPcMWZ9jDJZwv5AcK7LdLT+Lb3T/qKWMj3DfeOb3WJFX2NzSmd60fRsv0gPSnM/D3ZoXUMxVjs3MqMzv+P5+dJ0roHbGIWVV1FUB0="
  - secure: "ICbAc4rTINnujJdt/caFPEOwrtAKmFd+DGxlE0Hukn2WGUxrci5lvBU6LXoECS26yVApVzV8iYaz4IEz9n3EVc+VmzSpw+qmBBKmlfZBrfavtQpXoyXiXU/3eEc2sLRQtf5rc1nKZuIFQ6Y3MR5u1SFMFrMTiFqYKaXVRr/o93xoKILYoZkZ4aNu5OSNMtQ45PJKblxqf7fMxe/HHrKg9mTmpxJ/C4AA2kcRPCVLfPf9J5lKqor3GwVIrExUU1aJJlJtwtK8Uz5nSAHjNOA4RZ6qjVtkTKBIfbvaaPf42QwejUYf5M+WEXsTWLBpIKHetSus7ajzpv9SvbPHmxIDQPw9nRinZV2c206ublYQf3UCXJtm3RU8XbOLFUkTXEKjvw06i29lUojFsHqs0QA6xkY1tdIXILOgcb0t2sDGGhY5jE9TlANfOAVtHt5sNRVetCk1JA5RZXFfJz8umxkfyAbm/taVvI9aM48RhqO4iMygNwjVrOfAWOaT/x39e2Ra0ESrT1Z/czT0yHU4R6p+jOByncE6lnhOVFmRPb55Jz5l4WI2OIs0NZcFbYUVAEchJqg2aeER8Oi00339Y40/DofSiurp+pcWoftdzg1Xd1KShuv0caKLQf0NkSTiLO6ZL4vAb0fKV31m2jkJAmfR9cBObzf60V0uvIMaW8GNbhY="
  - secure: "PTDtuuVBQ+AwxfJ/H+eSsgPN2TZCVvr8EbZmF74ZA1mRSue8NAY4QiHcNqnnt8Shw2gDiWJ4MB0jNcSiHYi66iw5nSy8gmwJAy1eU9Scs5YikGLzHS2Pc2Vs/WzTKfVExmGpfw6xVxXufBGGKSHsTus1NFD69xGJ1RNjske0o9DF9VT244EoMEIRwaC9aoEVJ6N0Ns97kwXhX+abMKWS769pz7HhbfqKiVEgjdJ/3lIWtQEU30sV25QdI0F9UToL81usC6lWiXfw1sfzHttK9DIjjb2UGpfIsv2DqLuH9eRzAeXwFr7qsYycFHEhRlehW8wbwmvf50zKJfQq/Q5qKcs1aU4GnRaIcA2BE7kyV1jpLFqQTpOix0ZKKfIssUsWL5kstONN6DSEmG/t/6HxoBV/QHRyzv5lz2nLcT3LTi2V0Pq457ZejjK4Gtqbbr+4QBKOKf3GMULg9sWiv8gnwiwgPNtZYY4J8lU1xO7bvXU8RaKv44vPXXxRc6+11DhhIcD2ywW8LFNNFbFQsE2gxJktA+WCpprMywGZLdQ1k9+ZUbfTWV3A5JP4a0sQ5tr4KYj103Gdmux2GuU2rVv29ZKNpOR3pC+FnOXSm3Ft1Pkfxdt3sZ3twf2A7LScZAExcCuQdfU6QxPgbP3Gogpu/rgQSujGxOY17H++8Avrcbg="
  - secure: "QBlYuoYq6BU7EmmhtJ55tx1860uLmwa3AoDVavOB9aqh5sPQkG+NVIQZSmDc77GzUwGU0feJOAn0B3hhJ0D9R9xMd7z3htDYXB2MO8nATqJzJ9oyrBUFWv5o5SNf1JlQpqPephIGpmlRn8GxO/aJeGItoIv7Qttu56eDsFfqxz4rEcMv7YjXMDkCZme1vXprGGqOb5x5yFCmnc4DnjfEt0zXkJrEP1jA/bPu+DNTq/N+Ht0A1DnVxC2cjSUcodHuXzcOrM/3lNLrMYb+r5zHZI5MqN+Ou9Ief1gVgQdWQhCFZ14ofQj2svc/jjpWE1a2DifwxIoQiIDjxozSQJIPXckdd8uGtNcZFS+B+AMbxmaJkQs+BmAhoPvzYnkepRZkpNCOMVImjn6jeOi+iC69OzeCT0PF7j4JYWBpIulRso2qfH/pyBsq7QYcDQeTLkeE/FHmOvWnu6+vZmW/aU8N8Awez7vuJDYvWW/5JZMp3bWwXN2kateDGRayfEOUbE6GprTs7uv/xvIJC/amI0+YbGOIkvaoiWe3kTbL99gmszgUOp/YvDfbLVUonm97npfDlrU9uL+qqdnBrZzAHRGIZclb2Tn7agf3IAQN1KaxpFOL7u+VEG5HbtGEbh/h/oOyKMVcb8ho4lWauOcfy78N3f9VkKKr7gnVAEt+eueZbFQ="

# Secure Keys, that need to be set for snapshot builds
#
# PMD_SF_USER - the sourceforge user, which is used to upload created binaries to sf files section. Note: an ssh key is
#               required. See "before_install".

# Secure Keys, that need to be set for releases:
#
# BINTRAY_USER
# BINTRAY_APIKEY
# GITHUB_OAUTH_TOKEN
#

